import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// eslint-config-next already registers the jsx-a11y plugin but enables only a few rules
// as warnings. Reuse that plugin instance (a second copy would clash) and enforce its
// full recommended set, because keyboard and screen-reader support is a requirement.
const jsxA11y = nextVitals.find((config) => config.plugins?.["jsx-a11y"])?.plugins["jsx-a11y"];
if (!jsxA11y) {
  throw new Error("eslint-config-next no longer registers jsx-a11y; update eslint.config.mjs");
}

const AUTH_STORAGE_MESSAGE =
  "Do not use browser storage: Clerk owns the session and tokens must never be persisted. " +
  "For a non-auth preference, disable this rule on that line with a justification.";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      ...jsxA11y.configs.recommended.rules,
      eqeqeq: ["error", "always"],
      // Clerk owns the session. Tokens must never be copied into browser storage.
      "no-restricted-globals": [
        "error",
        { name: "localStorage", message: AUTH_STORAGE_MESSAGE },
        { name: "sessionStorage", message: AUTH_STORAGE_MESSAGE },
      ],
      // @clerk/nextjs v7 still exports these removed components.
      "no-restricted-imports": [
        "error",
        {
          paths: ["SignedIn", "SignedOut", "Protect"].map((name) => ({
            name: "@clerk/nextjs",
            importNames: [name],
            message: `<${name}> was removed in @clerk/nextjs v7 and throws at runtime. Use <Show> instead.`,
          })),
        },
      ],
      "no-restricted-properties": [
        "error",
        ...["window", "globalThis", "self"].flatMap((object) =>
          ["localStorage", "sessionStorage"].map((property) => ({
            object,
            property,
            message: AUTH_STORAGE_MESSAGE,
          })),
        ),
      ],
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },
  {
    // Type-aware rules catch unawaited requests.
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
    },
  },
  {
    // User-facing text lives in src/messages so it can be translated.
    files: ["src/app/**/*.tsx", "src/components/**/*.tsx"],
    ignores: ["src/components/ui/**"],
    rules: {
      "react/jsx-no-literals": [
        "error",
        { noStrings: true, allowedStrings: ["·", "…", "|", "-", "/", ":", " "], ignoreProps: true },
      ],
    },
  },
  {
    // node:test registers tests when test() is called at the top level.
    files: ["**/*.test.ts"],
    rules: { "@typescript-eslint/no-floating-promises": "off" },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `pnpm api:types`; regenerate instead of editing.
    "src/lib/api/schema.d.ts",
  ]),
]);

export default eslintConfig;
