/** The photo set by name; each name is a file in public/photos (made by scripts/photos.mjs from photos-original). */
export const PHOTOS = {
  hero: "hero-rooftop-golden-hour",
  installers: "installers-on-roof",
  technician: "technician-inverter-wall",
  consultation: "home-consultation",
  aerial: "aerial-town-rooftops",
  panelMacro: "panel-cell-macro",
  inverterCloseup: "inverter-closeup",
  cabling: "cabling-detail",
  sunrise: "sunrise-palms-panels",
  signIn: "auth-signin-morning-roof",
  signUp: "auth-signup-new-home",
  panelPlaceholder: "product-panel-placeholder",
  inverterPlaceholder: "product-inverter-placeholder",
  companyCover: "company-placeholder-cover",
  learnHow: "learn-how-solar-works",
  learnPanels: "learn-panels-inverters",
  learnDatasheet: "learn-datasheet",
  learnGrid: "learn-grid-connection",
  learnBill: "learn-electricity-bill",
  learnCleaning: "learn-cleaning-safely",
  learnTechnician: "learn-call-technician",
  siteSurvey: "journey-site-survey",
  delivery: "journey-delivery",
  installation: "journey-installation",
  handover: "journey-handover",
  safetyVisit: "help-safety-visit",
  photographDisplay: "help-photograph-display",
  errorSky: "error-sun-behind-clouds",
  shareCard: "share-card-background",
  roofPlan: "estimator-roof-plan",
  team: "companies-team",
  homeEvening: "customer-home-evening",
} as const;

export type PhotoKey = keyof typeof PHOTOS;
