import {
  Activity,
  BookOpen,
  Building2,
  CalendarClock,
  ClipboardList,
  Factory,
  FileText,
  Heart,
  Inbox,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  type LucideIcon,
  PackageSearch,
  SlidersHorizontal,
  Sun,
  Users,
  Wrench,
  Zap,
} from "lucide-react";

/** One small icon for each link in a signed-in area, so the side column can be scanned as well as read. */
export const NAV_ICONS: Record<string, LucideIcon> = {
  "my-dashboard": LayoutDashboard,
  "my-support": LifeBuoy,
  "my-estimates": LineChart,
  "my-requests": ClipboardList,
  "my-installations": Sun,
  "my-favourites": Heart,
  "technician-visits": CalendarClock,
  "technician-support": LifeBuoy,
  "company-dashboard": LayoutDashboard,
  "company-support": LifeBuoy,
  "company-inbox": Inbox,
  "company-offers": FileText,
  "company-installations": Wrench,
  "company-profile": Building2,
  "admin-companies": Factory,
  "admin-catalogue": PackageSearch,
  "admin-estimator": SlidersHorizontal,
  "admin-users": Users,
  "admin-troubleshooting": Zap,
  "admin-education": BookOpen,
  "admin-activity": Activity,
};
