import {
  Activity,
  Bell,
  BookOpen,
  Building2,
  CalendarClock,
  Calculator,
  ClipboardList,
  Cpu,
  Factory,
  FileText,
  FolderOpen,
  GraduationCap,
  Heart,
  Inbox,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  type LucideIcon,
  PackageSearch,
  Plus,
  Scale,
  ScrollText,
  ShieldAlert,
  SlidersHorizontal,
  Sun,
  SunMedium,
  User,
  Users,
  Wrench,
  Zap,
} from "lucide-react";

/** One small icon for each link in a signed-in area, so the side column can be scanned as well as read. */
export const NAV_ICONS: Record<string, LucideIcon> = {
  "my-dashboard": LayoutDashboard,
  "my-support": LifeBuoy,
  "my-estimates": LineChart,
  "my-requests": ClipboardList,
  "my-installations": Sun,
  "my-favourites": Heart,
  "technician-visits": CalendarClock,
  "technician-support": LifeBuoy,
  "company-dashboard": LayoutDashboard,
  "company-support": LifeBuoy,
  "company-inbox": Inbox,
  "company-offers": FileText,
  "company-installations": Wrench,
  "company-profile": Building2,
  "admin-companies": Factory,
  "admin-catalogue": PackageSearch,
  "admin-estimator": SlidersHorizontal,
  "admin-users": Users,
  "admin-troubleshooting": Zap,
  "admin-education": BookOpen,
  "admin-activity": Activity,
  "admin-home": LayoutDashboard,
  estimator: Calculator,
  panels: SunMedium,
  inverters: Cpu,
  "compare-panels": Scale,
  "compare-inverters": Scale,
  companies: Building2,
  "new-request": Plus,
  learn: BookOpen,
  troubleshooting: Zap,
  "safety-help": ShieldAlert,
  notifications: Bell,
  account: User,
};

/** One icon for each sidebar category, shown beside its name. */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  overview: LayoutDashboard,
  plan: Calculator,
  catalogue: SunMedium,
  installers: Building2,
  requests: Inbox,
  offers: FileText,
  installation: Sun,
  visits: CalendarClock,
  review: ClipboardList,
  content: FolderOpen,
  settings: SlidersHorizontal,
  people: Users,
  audit: ScrollText,
  company: Building2,
  learn: GraduationCap,
  help: LifeBuoy,
  account: User,
};
