// Makes the web-ready photos: reads the PNG masters in photos-original/, writes sized WebP files to public/photos/ and a manifest the app reads.
import { createRequire } from "node:module";
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const sharp = createRequire(createRequire(import.meta.url).resolve("next/package.json"))("sharp");
const SOURCE = "photos-original";
const OUT = "public/photos";
const WIDTHS = [480, 960, 1440, 1920];
const QUALITY = 78;

mkdirSync(OUT, { recursive: true });
for (const name of readdirSync(OUT)) rmSync(join(OUT, name));

const manifest = {};
for (const file of readdirSync(SOURCE).filter((name) => /\.(png|jpe?g|webp)$/i.test(name)).sort()) {
  const base = file.replace(/\.[^.]+$/, "");
  const input = sharp(join(SOURCE, file));
  const { width, height } = await input.metadata();
  const widths = [...WIDTHS.filter((w) => w < width), width];
  for (const w of widths) await sharp(join(SOURCE, file)).resize({ width: w }).webp({ quality: QUALITY }).toFile(join(OUT, `${base}-${w}.webp`));
  const tiny = await sharp(join(SOURCE, file)).resize({ width: 20 }).jpeg({ quality: 50 }).toBuffer();
  manifest[base] = { width, height, widths, blur: `data:image/jpeg;base64,${tiny.toString("base64")}` };
}

const lines = Object.entries(manifest).map(([name, entry]) => `  "${name}": { width: ${entry.width}, height: ${entry.height}, widths: [${entry.widths.join(", ")}], blur: "${entry.blur}" },`);
writeFileSync("src/lib/photos/manifest.ts", `// Generated by scripts/photos.mjs; do not edit by hand.\nexport interface PhotoFile {\n  width: number;\n  height: number;\n  widths: number[];\n  blur: string;\n}\n\nexport const PHOTO_FILES: Record<string, PhotoFile> = {\n${lines.join("\n")}\n};\n`);
process.stdout.write(`${Object.keys(manifest).length} photos, ${readdirSync(OUT).length} files\n`);
